refactor
OMNI-SLO-Monitoring/account-service pull request #2
Opened 2020-08-06 08:37 UTC by JonasJW

## Preparations
Please check if the PR fulfills these requirements
- [x] Readme (How to Install, Run, Use and Configure) wurde aktualisiert falls nötig
- [x] Das Feature ist dokumentiert
- [x] Alle nicht getter und setter Methoden sind dokumentiert
- [ ] Es wurden Unit tests für neue Features erstellt
- [ ] Alle Tests müssen erfolgreich sein
- [ ] Mindestens ein Reviewer muss den Pull Request akzeptieren

## :ticket: Description

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- layout changes
- request results are displayed like a console
- errors are highlighted red
- refactor

* **What is the current behavior?** (You can also link to an open issue here)
- results are shown as json
- no error highlighting

* **What is the new behavior (if this is a feature change)?**
see above

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:

## :lock: Closes
Which issue(s) is (are) being closed by the PR?

2020-08-06 14:29 UTC, stiesssh commented
laut README läuft der service auf port 4200. tatsächlich ist es aber port 4100. bitte angleichen!

2020-08-06 14:33 UTC, stiesssh requested changes
laut README läuft der service auf port 4200. tatsächlich ist es aber port 4100. bitte angleichen!

2020-08-11 09:18 UTC, JonasJW commented
> laut README läuft der service auf port 4200. tatsächlich ist es aber port 4100. bitte angleichen!

Es handelt sich hier ja um ein Angular Projekt, also ist der port standardmäßig auf 4200 und es wurde auch (soweit ich weiß) nirgends ein port festgelegt, deshalb verstehe ich nicht wieso es bei dir auf 4100 läuft, außer wenn du `ng serve --port 4100` gemacht hast.

2020-08-12 05:14 UTC, stiesssh commented
interessant o_O 
aber wenn das nur bei mit unter port 4100 läuft, passt dass natürlich. (vielleicht lieg im hintergrund noch was auf 4200 oder so...)

2020-08-12 05:14 UTC, stiesssh submitted a review, later dismissed

2020-08-12 05:21 UTC, stiesssh commented
korrigiere, schau mal in die angular.json. ich denke das läuft absichtlich unter 4100:

`        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "account-service-frontend:build",
            "port": 4100
          },`

2020-08-12 07:24 UTC, JonasJW commented
Tatsächlich, dann hat das bestimmt jemand geändert, ich habs in der Readme geupdated

2020-08-12 15:36 UTC, stiesssh approved these changes

2020-08-13 07:39 UTC, merged